### ISSUE TITLE
Contributions and library status

### ISSUE THREAD

**Issue by enzoferey** [spothq/cryptocurrency-icons#412]
Hi @tommdn 👋🏻 

I'm currently working on a product that is about to be released and we are heavily relying on this library to display coin logos and map their name from their symbol.

I have of course noticed that some of the newest (and trendy) coins are missing. To name a few, `PSG`, `NKN` or `CHZ` have been moving quite a bit for the last few days and are not part of the collection.

I have also seen the many issues opened for a while to add more coins to the list and to do other little improvements, and I was wondering if there is any motivation for maintainers here to push the library forwards if I start contributing heavily to it or if I should much rather fork it (or is there a better fork/alternative already ?).

Looking forward to hearing from you 🙌🏻

**Comment by tommdn** [comment]
@enzoferey hello. The icons are done by batches, prioritizing the most requested (this is the reason why some old issues are still there). It takes some time to create those icons — I am trying (as far as possible) to stay agnostic to make the set coherent.

I do not know a better library yet (at least of this quality, this icon set has the best optical centering for sure). What I would suggest is to add new requests if you need more coins, and use placeholders in your product for the in-between. Next batch is coming very soon, and if you make the issues I will see if we can slide those in.

As mentioned we do not accept pull requests for new or updated icons at the time (mainly because it would take more time to review a contribution than making the actual icon), so open a new issue and we will do the icon for you. If you absolutely need one particular icon and cannot wait for the next batch you can fork this repository.

**Comment by enzoferey** [comment]
Thanks for your quick answer. 

I totally understand your batch approach. Based on the git history, I can see you are updating every ~3 months, which in a rapidly changing environment like cryptos doesn't sound enough to me 😅 

I wonder what kind of pipeline these icons go through ? In the issues I already see SVG files, and most coins provide them as product would provide their logos for media. Could I eventually help you on executing batches more frequently ? I definitely understand that optical centering is important and relative sizing among them as well -- I think I'm totally capable of achieving so.

Let me know 👍🏻

**Comment by tommdn** [comment]
@enzoferey it could definitely be faster indeed. Currently batches are done when I can find time to do them.

The initial contributor described a pipeline which is quite accurate regarding how I'm making the batches today. You will find it here: https://github.com/spothq/cryptocurrency-icons/wiki. However it is quite outdated and images are missing.

I appreciate your offer — it would be really nice to have another contributor here. I'm pinging you in DM so we can take a look at if we can make this work.
