### ISSUE TITLE
ETH Logo is off centre

### ISSUE THREAD

**Issue by ricburton** [spothq/cryptocurrency-icons#496]
<img width="559" alt="CleanShot 2022-03-08 at 11 51 28@2x" src="https://user-images.githubusercontent.com/438160/157314227-3d12a67d-b299-4693-8de9-7a25d60acef0.png">

**Comment by ricburton** [comment]
<img width="1502" alt="CleanShot 2022-03-08 at 12 00 41@2x" src="https://user-images.githubusercontent.com/438160/157315499-6d3e0e90-7b82-4e72-87e6-b08559c96ff9.png">

**Comment by tommdn** [comment]
Hello @ricburton, thanks for the feedback. I did not design this icon initially, but I took the time to review it carefully.
I think this is intended. But the applied offset is however a little bit off.

I tried the example you have shown and it is off-centered as well (to the left this time). Given the alpha blending asymmetry, the icon needs to be offset to the right in order to correctly distribute its mass. That is easier to see when the icon is small: I'm always doing optical centering by reducing the size dramatically.

Applying an offset of `.75` (instead of `1` currently) seems correct in this case (in short, if I had to put an integer I would have chosen `1` like the original).

<img width="580" alt="ETH" src="https://user-images.githubusercontent.com/11268305/157333268-1c715a88-1995-4cb5-b32c-b47b3aad9c4e.png">

Please take a look and tell me if that makes sense to you.

I can see in your example that you reduced the size of the icon as well. Maybe we can settle it this way: a smaller icon, with `.75` — let me know what you think.

**Comment by ricburton** [comment]
I have not given an example SVG yet :)

Want me to export and send over?

Glad to see the project accepts contributions.

**Comment by ricburton** [comment]
![image](https://user-images.githubusercontent.com/438160/157337507-2bdb2f05-4b9a-4dc4-9b3c-07a83d3654e8.jpeg)

You need to slightly scale the ETH logo up by a pixel.

**Comment by tommdn** [comment]
> I have not given an example SVG yet :)

I was talking about the image you have uploaded with on the left side the current state of the `ETH` icon, on the right side your version which is horizontally centered (and with a smaller icon size). Seems to be the "Scaled down" version from the second image. Isn't it?

> Glad to see the project accepts contributions.

Well, as mentioned in the README, the previous contributors added the part saying pull requests are not accepted. Mainly because it takes more time to fix an icon than to make it. But I'm pleased to see suggestions like yours — those are always welcome.

I'm not sure I totally understand the image you have just uploaded here. There are three different topics.

- First, what aspect ratio we choose. If the aspect ratio is not conform to the Ethereum branding one, then the one who made the icon did a mistake and we indeed need to change it.
- Next, regarding the size in the circle I understand you would prefer the icon to be larger in the circle. I'm not opposed to it but it should look harmonious with the other icons (for example `ADX` has a comparable surface).
- Regardless of the aspect ratio or icon size, the point of my first answer was that the icon should **not** be horizontally centered. One of the main value of this repository is optical centering and this is in most cases **not** pure horizontal or vertical centering.

Please give me answers on each of those three points so we can break down the problem.

**Comment by ricburton** [comment]
Here you go
![eth](https://user-images.githubusercontent.com/438160/157351097-1abf253b-946c-4cfc-bbd7-f3c0f325248f.svg)
!

I can compress it too if that helps. But this is *perfectly* in the middle.

**Comment by ricburton** [comment]
![Slice](https://user-images.githubusercontent.com/438160/157351195-dd0768d3-b61f-4f08-9b75-2a0eef4b302b.png)
Explaining the thinking more.

ETH is the most popular asset

**Comment by syeo66** [comment]
I think the the offset is intentional because of the pixel distribution of small sizes. Having even numbers (16px, 24px) you do not have a center pixel which would make an edge exactly on the center more blurry due to interpolation. So, by applying an offset the edge starts getting more pronounced on one of the sides and thus looks sharper even on really small sizes.
